webapp/appr_type/models.py
from webapp.db import db


class Approved_types(db.Model):
    """
    Description of the table of approved types of measuring instruments
    """
    id_appr_type = db.Column(db.Integer, primary_key=True)
    number_si = db.Column(db.String(10), nullable=False)
    name_si = db.Column(db.Text)
    designation_si = db.Column(db.Text)
    number_record = db.Column(db.Integer)
    id_arshin = db.Column(db.Integer, unique=True, nullable=False)
    publication_date = db.Column(db.Date)
    manufacturer_si = db.Column(db.String)
    description_si = db.Column(db.String)
    method_verif_si = db.Column(db.String)
    proced_si = db.Column(db.String)
    certificate_date = db.Column(db.Date)
    mpi_si = db.Column(db.String(20))
    next_verif_si = db.Column(db.Boolean)
    part_verif_si = db.Column(db.Boolean)
    status_si = db.Column(db.String)
    tasks = db.relationship('Tasks', backref='tasks_appr_type', lazy='dynamic')


class Verification_data(db.Model):
    """
    Description of the table storing json files for the approved types
    """
    id_appr_type = db.Column(db.Integer, primary_key=True)
    model_si = db.Column(db.String(1024), nullable=False)
    ver_data = db.Column(db.VARCHAR(), nullable=False)

webapp/appr_type/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    """
    Search form
    """
    number_mi = StringField(
        'Номер в госреестре',
        render_kw={"class": "form-control me-1",
                   "placeholder": "Номер в госреестре"}
    )
    submit = SubmitField(
        'Поиск',
        render_kw={"class": "btn btn-primary search"}
    )

webapp/appr_type/views.py
import os
from flask import Blueprint, render_template, request, redirect, url_for

from webapp.appr_type.models import Approved_types
from webapp.appr_type.forms import SearchForm


blueprint = Blueprint('appr_types', __name__, url_prefix='/appr_types')


@blueprint.route('/', methods=['GET'], defaults={"page": 1})
@blueprint.route('/<int:page>', methods=['GET'])
def appr_types(page):
    """
    This page contains a table with approved types of measuring instruments
    with the ability to navigate through the pages

    :param page: page number
    """
    per_page = 20
    title = 'Утвержденные типы СИ'
    search_form = SearchForm()
    pagination = Approved_types.query. \
        order_by(Approved_types.id_appr_type.desc()). \
        paginate(page=page, per_page=per_page, error_out=False)

    return render_template(
        'appr_types/appr_types.html',
        page_title=title,
        form=search_form,
        pagination=pagination
    )

@blueprint.route('/search/<string:number_mi>/', methods=['GET'], defaults={"page": 1})
@blueprint.route('/search/<string:number_mi>/<int:page>', methods=['GET'])
def search_appr_type(number_mi, page):
    """
    This page
    """
    per_page = 20
    title = 'Утвержденные типы СИ'
    search_form = SearchForm()
    pagination = Approved_types.query. \
        filter(Approved_types.number_si.like(f'%{number_mi}%')). \
        paginate(page=page, per_page=per_page, error_out=False)

    return render_template(
        'appr_types/search_appr_type.html',
        page_title=title,
        form=search_form,
        pagination=pagination,
        number_mi=number_mi
    )


@blueprint.route('/process-search', methods=['POST'])
def process_search():
    """
    This page
    """
    search_form = SearchForm()
    if search_form.validate_on_submit():
        number_mi = str(search_form.number_mi.data)
        if number_mi != '':
            return redirect(url_for('appr_types.search_appr_type',
                                    number_mi=number_mi,
                                    page=1))

    return redirect(url_for('appr_types.appr_types'))


@blueprint.route('/info/<int:id_appr_type>')
def appr_type_info(id_appr_type):
    """
    This page contains all the information about one approved type
    of measuring instrument

    :param id_appr_type: id of approved type from db.Approved_types
    """
    data_of_appr_type = Approved_types.query.get(id_appr_type)
    title = f'Сведения об утвержденном типе СИ ({data_of_appr_type.number_si})'
    file = f'webapp/appr_type/scripts/{data_of_appr_type.number_si}.json'
    status_file = os.path.exists(file)
    back_page_url = request.referrer
    

    return render_template(
        'appr_types/data_of_appr_type.html',
        data_of_appr_type=data_of_appr_type,
        page_title=title,
        status_file=status_file,
        back_page_url=back_page_url
    )

webapp/templates/appr_types/appr_types.html
{% extends "base.html" %}

{% block content %}
	<div class="scroll-table">
		<form class="d-flex search" action="{{ url_for('appr_types.process_search') }}" method="POST">
			{{ form.hidden_tag() }}
				{{ form.number_mi() }}
				{{ form.submit() }}
		</form>
		
		<nav aria-label="Page navigation" class="navigation_page">
			<ul class="pagination pagination-sm">
				<li class="page-item {% if not pagination.has_prev %} disabled {% endif %}">
					<a class="page-link" href="{{ url_for('appr_types.appr_types', page=pagination.prev_num) }}" aria-label="Предыдущая">
						<span aria-hidden="true">&laquo;</span>
					</a>
				</li>
	
				{% for page in pagination.iter_pages(left_edge=1, left_current=2, right_current=2, right_edge=1) %}
					{% if page %}
					<li class="page-item {%if page==pagination.page%} active {%endif%}">
						<a class="page-link" href="{{ url_for('appr_types.appr_types', page=page) }}">{{page}}</a>
					</li>
					{% else %}
					<li class="page-item disabled">
						<a class="page-link" href="#">&hellip;</a>
					</li>
					{% endif %}
				{% endfor %}
	
				<li class="page-item {% if not pagination.has_next %} disabled {% endif %}">
					<a class="page-link" href="{{ url_for('appr_types.appr_types', page=pagination.next_num) }}" aria-label="Следующая">
						<span aria-hidden="true">&raquo;</span>
					</a>
				</li>
			</ul>
		</nav>

		<table class="mainTable table-scroll" id="tableId1"> 
			<thead>
				<tr>
					<th style="text-align:center;"><input type="checkbox" name="set" onclick="checkboxes_sel_all(this)"></th>
					<th class="column_2" data-order="-1" class="sorted">Номер в госреестре</th>
					<th class="column_3" data-order="-1">Наименование СИ</th>
					<th class="column_4">Обозначение типа СИ</th>
					<th class="column_5">Изготовитель</th>
				</tr>
			</thead>
			<tbody class="fixed">
				{% for appr_type in pagination.items %}
				<tr>
					<td style="text-align:center;"><input type="checkbox"></td>
					<td class="column_data_2">
						<a href="/appr_types/info/{{ appr_type.id_appr_type }}">{{ appr_type.number_si }}</a>
					</td>
					<td class="column_data_3">{{ appr_type.name_si }}</td>
					<td class="column_data_4">{{ appr_type.designation_si }}</td>
					<td class="column_data_5">{{ appr_type.manufacturer_si }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

webapp/templates/appr_types/data_of_appr_type.html
{% extends "base.html" %}

{% block content %}
	<div class="btn_info_appr_type">
		<a class="btn btn-secondary btn-sm btn_appr_type" href="{{ back_page_url }}" role="button">Назад</a>
		{% if status_file %}
			{% if current_user.is_authenticated %}
				<a href="/tasks/create_task/{{ data_of_appr_type.number_si }}" class="button">
					<div class="button__line"></div>
					<div class="button__line"></div>
					<span class="button__text">Начать поверку</span>
				</a>
			{% else %}
				<a href="/users/login" class="button">
					<div class="button__line"></div>
					<div class="button__line"></div>
					<span class="button__text">Начать поверку</span>
				</a>
			{% endif %}
		{% endif %}
	</div>

	<div>
		<table class="table_info">
			<thead>
				<tr>
					<th class="column_1">Наименование</th>
					<th class="column_2">Значение</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Номер в госреестре</td>
					<td>{{ data_of_appr_type.number_si }}</td>
				</tr>
				<tr>
					<td>Наименование СИ</td>
					<td>{{ data_of_appr_type.name_si }}</td>
				</tr>
				<tr>
					<td>Обозначение типа СИ</td>
					<td>{{ data_of_appr_type.designation_si }}</td>
				</tr>
				<tr>
					<td>Номер записи</td>
					<td>{{ data_of_appr_type.number_record }}</td>
				</tr>
				<tr>
					<td>Дата опубликования</td>
					<td>{{ data_of_appr_type.publication_date }}</td>
				</tr>
				<tr>
					<td>Изготовитель</td>
					<td>{{ data_of_appr_type.manufacturer_si }}</td>
				</tr>
				<tr>
					<td>Описание типа</td>
					<td><a href="{{ data_of_appr_type.description_si }}">ОТ_{{ data_of_appr_type.number_si }}.pdf</a></td>
				</tr>
				<tr>
					<td>Методика поверки</td>
					<td><a href="{{ data_of_appr_type.method_verif_si }}">МП_{{ data_of_appr_type.number_si }}.pdf</a></td>
				</tr>
				<tr>
					<td>Процедура</td>
					<td>{{ data_of_appr_type.proced_si }}</td>
				</tr>
				<tr>
					<td>Межповерочный интервал</td>
					<td>{{ data_of_appr_type.mpi_si }}</td>
				</tr>
				<tr>
					<td>Статус</td>
					<td>{{ data_of_appr_type.status_si }}</td>
				</tr>
				<tr>
					<td>Ссылка на АРШИН</td>
					<td><a href="https://fgis.gost.ru/fundmetrology/registry/4/items/{{ data_of_appr_type.id_arshin }}">{{ data_of_appr_type.number_si }}</a></td>
				</tr>
			</tbody>
		</table>
	</div>
{% endblock %}

webapp/templates/appr_types/search_appr_type.html
{% extends "base.html" %}

{% block content %}
	<div class="scroll-table">
		<form class="d-flex search" action="{{ url_for('appr_types.process_search') }}" method="POST">
			{{ form.hidden_tag() }}
				{{ form.number_mi(value=number_mi) }}
				{{ form.submit() }}
		</form>
		
		<nav aria-label="Page navigation" class="navigation_page">
			<ul class="pagination pagination-sm">
				<li class="page-item {% if not pagination.has_prev %} disabled {% endif %}">
					<a class="page-link" href="{{ url_for('appr_types.search_appr_type', number_mi=number_mi, page=pagination.prev_num) }}" aria-label="Предыдущая">
						<span aria-hidden="true">&laquo;</span>
					</a>
				</li>
	
				{% for page in pagination.iter_pages(left_edge=1, left_current=2, right_current=2, right_edge=1) %}
					{% if page %}
					<li class="page-item {%if page==pagination.page%} active {%endif%}">
						<a class="page-link" href="{{ url_for('appr_types.search_appr_type', number_mi=number_mi, page=page) }}">{{page}}</a>
					</li>
					{% else %}
					<li class="page-item disabled">
						<a class="page-link" href="#">&hellip;</a>
					</li>
					{% endif %}
				{% endfor %}
	
				<li class="page-item {% if not pagination.has_next %} disabled {% endif %}">
					<a class="page-link" href="{{ url_for('appr_types.search_appr_type', number_mi=number_mi, page=pagination.next_num) }}" aria-label="Следующая">
						<span aria-hidden="true">&raquo;</span>
					</a>
				</li>
			</ul>
		</nav>

		<table class="mainTable table-scroll" id="tableId1"> 
			<thead>
				<tr>
					<th style="text-align:center;"><input type="checkbox" name="set" onclick="checkboxes_sel_all(this)"></th>
					<th class="column_2" data-order="-1" class="sorted">Номер в госреестре</th>
					<th class="column_3" data-order="-1">Наименование СИ</th>
					<th class="column_4">Обозначение типа СИ</th>
					<th class="column_5">Изготовитель</th>
				</tr>
			</thead>
			<tbody class="fixed">
				{% for appr_type in pagination.items %}
				<tr>
					<td style="text-align:center;"><input type="checkbox"></td>
					<td class="column_data_2">
						<a href="/appr_types/info/{{ appr_type.id_appr_type }}">{{ appr_type.number_si }}</a>
					</td>
					<td class="column_data_3">{{ appr_type.name_si }}</td>
					<td class="column_data_4">{{ appr_type.designation_si }}</td>
					<td class="column_data_5">{{ appr_type.manufacturer_si }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}