webapp/verification/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, HiddenField


class VerificationForm(FlaskForm):
    """
    Verification form
    """
    submit = SubmitField(
        'Завершить поверку',
        render_kw={"class": "btn btn-lg verification"}
    )

webapp/verification/views.py
from flask import Blueprint, flash, redirect, render_template, url_for, request
from flask_login import current_user

from webapp.verification.scripts.json_parser import DictConstructor
from webapp.verification.forms import VerificationForm


blueprint = Blueprint('verification', __name__, url_prefix='/verification')


@blueprint.route('/<string:number_mi>/<string:model>')
def verification_mi(number_mi: str, model: str):
    """
    This page is intended for verification of the measuring instrument

    :param number_mi: number in the state register
    :param model: name of the measuring instrument model
    """
    title = f'Поверка {model} ({number_mi})'
    data_of_verification = DictConstructor(
        number_mi,
        model.lower()
    ).dict_for_html
    verification_form = VerificationForm()

    return render_template(
        'verification/verification.html',
        page_title=title,
        verification=data_of_verification,
        form=verification_form
    )


@blueprint.route('/get-result', methods=['POST'])
def get_result():
    """
    This page is used to receive verification results entered by the user
    """
    verification_form = VerificationForm()
    if verification_form.validate_on_submit():
        id_user = current_user.id
        result_task = {
            'limit': request.form.getlist('limit'),
            'point': request.form.getlist('point'),
            'freq': request.form.getlist('freq'),
            'meas_result': request.form.getlist('meas_result'),
            'abs_error': request.form.getlist('abs_error'),
            'meas_error': request.form.getlist('meas_error'),
            'result_meas': request.form.getlist('result_meas')
        }
        print(result_task)
        flash('Данные о поверке успешно получены')

        return redirect(url_for('tasks.task_manager'))

    flash('Что-то пошло не так')
    return redirect(url_for('verification.verification_mi'))

webapp/templates/verification/verification.html
{% extends "base.html" %}

{% block content %}
	{% with messages = get_flashed_messages() %}
		{% if messages %}
			<div class="alert alert-warning" role="alert">
				{% for message in messages %}
					{{ message }}<br>
				{% endfor %}
			</div>
		{% endif %}
	{% endwith %}

	<form action="{{ url_for('verification.get_result') }}" method="POST">
		{{ form.hidden_tag() }}
		<div class="poverka">
			<h4 name="header">{{ verification.header }}</h4>
			<div>
				<ol class="multilevel">
					{% set id, num = namespace(x=1), namespace(x=1) %}
					{% for main_operation in verification.main_operations %}
						<li>
							<a class="header">{{ main_operation.item_name }}:</a>
							<div class="form_radio">
								<div class="form_radio_btn item-1">
									<input id="radio-{{id}}" type="radio" name="radio_{{num}}" value="1" checked>
									<label for="radio-{{id}}">{{ main_operation.positive_result }}</label>
								</div>
								{% set id.x = id.x + 1 %}
								<div class="form_radio_btn item-2">
									<input id="radio-{{id}}" type="radio" name="radio_{{num}}" value="2">
									<label for="radio-{{id}}">{{ main_operation.negative_result }}</label>
								</div>
								{% set id.x = id.x + 1 %}
							</div>
							{% set num.x = num.x + 1 %}
							<p></p>
						</li>
					{% endfor %}
					<li>
						<a class="header">Определение метрологических характеристик</a>
						<ol> 
							{% for metrolog_operation in verification.metrolog_operations %}
							<li>
								<a class="header">{{ metrolog_operation.table_name }}</a>
								
								<table class="verificationTable">
									<thead>
										<tr>
											{% for header in metrolog_operation.headers %}
												<th class="column_x">{{ header }}</th>
											{% endfor %}
										</tr>
									</thead>
									{% for row in metrolog_operation.rows %}
										<tbody>
											<tr>
												{% for point in row %}
													{% if point[1] == "limit" %}
														<td class="column_data_x">
															<input class="input_dis" name="limit" value="{{ point[0] }}" readonly="readonly">
														</td>
													{% elif point[1] == "point" %}
														<td class="column_data_x">
															<input class="input_dis" name="point" value="{{ point[0] }}" readonly="readonly">
														</td>
													{% elif point[1] == "freq" %}
														<td class="column_data_x">
															<input class="input_dis" name="freq" value="{{ point[0] }}" readonly="readonly">
														</td>
													{% elif point[1] == "input_value" %}
														<td class="column_data_x">
															<input class="input_point" value="{{ point[0] }}" name="meas_result" onkeydown="if(event.keyCode==13){return false;}">
														</td>
													{% elif point[1] == "abs_error" %}
														<td class="column_data_x">
															<input class="input_dis" name="abs_error" value="{{ point[0] }}" readonly="readonly">
														</td>
													{% elif point[1] == "meas_error" %}
														<td class="column_data_x">
															<input class="input_dis" name="meas_error" value="{{ point[0] }}" readonly="readonly">
														</td>
													{% elif point[1] == "result" %}
														<td class="column_data_x">
															<input class="input_dis" name="result_meas" value="{{ point[0] }}" readonly="readonly">
														</td>
													{% endif %}
												{% endfor %}
											</tr>
										</tbody>
									{% endfor %}
								</table>
								<p></p>
							</li>
							{% endfor %}
						</ol>
					</li>
				</ol>
			</div>
		</div>

		<!-- Submit-->
		<div class="verification-submit">
			{{ form.submit() }}
		</div>
	</form>
{% endblock %}

webapp/templates/verification/verification_new.html
{% extends "base.html" %}

{% block content %}
	{% with messages = get_flashed_messages() %}
		{% if messages %}
			<div class="alert alert-warning" role="alert">
				{% for message in messages %}
					{{ message }}<br>
				{% endfor %}
			</div>
		{% endif %}
	{% endwith %}

	<form action="{{ url_for('verification.get_result') }}" method="POST">
		{{ form.hidden_tag() }}
		<div class="poverka">
			<h4 name="header">{{ verification.header }}</h4>
			<div>
				<ol class="multilevel">
					{% set id, num = namespace(x=1), namespace(x=1) %}
					{% for main_operation in verification.main_operations %}
						<li>
							<a class="header">{{ main_operation.item_name }}:</a>
							<div class="form_radio">
								<div class="form_radio_btn item-1">
									<input id="radio-{{id}}" type="radio" name="radio_{{num}}" value="1" checked>
									<label for="radio-{{id}}">{{ main_operation.positive_result }}</label>
								</div>
								{% set id.x = id.x + 1 %}
								<div class="form_radio_btn item-2">
									<input id="radio-{{id}}" type="radio" name="radio_{{num}}" value="2">
									<label for="radio-{{id}}">{{ main_operation.negative_result }}</label>
								</div>
								{% set id.x = id.x + 1 %}
							</div>
							{% set num.x = num.x + 1 %}
							<p></p>
						</li>
					{% endfor %}
					<li>
						<a class="header">Определение метрологических характеристик</a>
						<ol> 
							{% for metrolog_operation in verification.metrolog_operations %}
							<li>
								<a class="header">{{ metrolog_operation.table_name }}</a>
								
								<table class="verificationTable" id ="tableBox">
									<thead>
										<tr>
											{% for header in metrolog_operation.headers %}
												<th class="column_x">{{ header }}</th>
											{% endfor %}
										</tr>
									</thead>
									{% for row in metrolog_operation.rows %}
										<tbody>
											<tr>
												{% for point in row %}
													{% if point[1] == "limit" %}
														<td class="column_data_x">{{ point[0] }}</td>
													{% elif point[1] == "point" %}
														<td class="column_data_x4"><a name="points">{{ point[0] }}</a></td>
													{% elif point[1] == "freq" %}
														<td class="column_data_x">{{ point[0] }}</td>
													{% elif point[1] == "input_value" %}
														<td class="column_data_x5"><input class="input_point" id="MeasResult" value="{{ point[0] }}" name="meas_result" onkeydown="if(event.keyCode==13){return false;}" ></td>
													{% elif point[1] == "abs_error" %}
														<td class="column_data_x2">{{ point[0] }}</td>
													{% elif point[1] == "meas_error" %}
														<td class="column_data_x">{{ point[0] }}</td>
													{% elif point[1] == "result" %}
														<td class="column_data_x">{{ point[0] }}</td>
													{% endif %}
												{% endfor %}
											</tr>
										</tbody>
									{% endfor %}
								</table>
								<p></p>
							</li>
							{% endfor %}
						</ol>
					</li>
				</ol>
			</div>
		</div>

		<!-- Submit-->
		<div class="verification-submit">
			{{ form.submit() }}
		</div>
	</form>
{% endblock %}