webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.db import db


class User(db.Model, UserMixin):
    """
    Description of the table of registered users
    """
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50))
    surname = db.Column(db.String(50))
    email = db.Column(db.String(50), index=True, unique=True)
    password = db.Column(db.String(128))
    organization = db.Column(db.String(256))
    role = db.Column(db.String(10), index=True)
    tasks = db.relationship('Tasks', backref='tasks', lazy='dynamic')

    def set_password(self, password):
        """
        The function to set the hash for the user's password

        :param password: the user's password
        """
        self.password = generate_password_hash(password)

    def check_password(self, password) -> bool:
        """
        The function compares the password entered by the user
        with the registered hash for the user's password in the database

        :param password: the user's password
        :return: comparison result as boolean
        """
        return check_password_hash(self.password, password)

    @property
    def is_admin(self) -> bool:
        """
        The function checks if the user is an administrator

        :return: validation result as boolean
        """
        return self.role == 'admin'

    def __repr__(self) -> str:
        """
        This function displays on the command line the data of the user
        who has just logged into the application

        :return: string with username, surname and email
        """
        return '<User {} {}, email {}>'.format(self.username, self.surname, self.email)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, EmailField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError

from webapp.user.models import User


class LoginForm(FlaskForm):
    """
    User login form
    """
    email = EmailField(
        'Почта',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg"}
    )
    password = PasswordField(
        'Пароль',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg"}
    )
    remember_me = BooleanField(
        'Запомнить меня',
        validators=[DataRequired()],
        default=True,
        render_kw={"class": "form-check-input login"}
    )
    submit = SubmitField(
        'Войти',
        render_kw={"class": "btn btn-lg login"}
    )


class RegistrationForm(FlaskForm):
    """
    User registration form
    """
    username = StringField(
        'Имя пользователя',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg"}
    )
    surname = StringField(
        'Фамилия пользователя',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg"}
    )
    organization = StringField(
        'Организация',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg"}
    )
    email = EmailField(
        'Почта',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg"}
        )
    password = PasswordField(
        'Пароль',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg"}
    )
    submit = SubmitField(
        'Зарегистрироваться',
        render_kw={"class": "btn btn-lg registration-user"}
    )

    def validate_email(self, email):
        """
        Function to check for the existence of a user with the same email

        :param email: entered email
        """
        users_count = User.query.filter_by(email=email.data).count()
        if users_count > 0:
            raise ValidationError(
                'Пользователь с такой почтой уже зарегистрирован!'
            )

webapp/user/views.py
from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user

from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.db import db


blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    """
    This page contains user authorization
    """
    if current_user.is_authenticated:
        return redirect(url_for('main_page'))

    title = 'Авторизация пользователя'
    login_form = LoginForm()

    return render_template(
        'user/login.html',
        page_title=title,
        form=login_form
    )


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    """
    This page checks the data entered by the user for authorization
    """
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.email == form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Авторизация выполнена!')

            return redirect(url_for('main_page'))

    flash('Неправильная почта или пароль!')

    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    """
    This page logs out the current user
    """
    logout_user()

    return redirect(url_for('main_page'))


@blueprint.route('/registration')
def registration():
    """
    This page contains the registration of a new user
    """
    if current_user.is_authenticated:
        return redirect(url_for('main_page'))

    title = 'Регистрация пользователя'
    registration_form = RegistrationForm()

    return render_template(
        'user/registration.html',
        page_title=title,
        form=registration_form
    )


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    """
    This page checks the data entered by the user for registration on the site
    and returns an error if the user is already registered
    """
    registration_form = RegistrationForm()
    if registration_form.validate_on_submit():
        new_user = User(
            username=registration_form.username.data,
            surname=registration_form.surname.data,
            email=registration_form.email.data,
            organization=registration_form.organization.data,
            role='user'
        )
        new_user.set_password(registration_form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')

        return redirect(url_for('user.login'))

    for field, errors in registration_form.errors.items():
        for error in errors:
            flash(error)

    return redirect(url_for('user.registration'))

webapp/templates/user/login.html
{% extends "base.html" %}

{% block content %}
	<section class="vh-80">
		<div class="container-fluid h-custom">
			<div class="row d-flex justify-content-center align-items-center">
			<div class="col-md-9 col-lg-6 col-xl-5">
				<img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
				class="img-fluid" alt="Sample image">
			</div>
			<div class="col-xl-4 offset-xl-1">
				<p style="margin-bottom: 5em"></p>
				<p class="text-center h2 fw-bold mb-5 mx-1 mx-md-4 mt-4">Вход</p>
				{% with messages = get_flashed_messages() %}
					{% if messages %}
					<div class="alert alert-warning" role="alert">
						{% for message in messages %}
							{{ message }}<br>
						{% endfor %}
					</div>
					{% endif %}
				{% endwith %}
				<form action="{{ url_for('user.process_login') }}" method="POST">
					{{ form.hidden_tag() }}

					<!-- Email input -->
					<div class="form-outline mb-2">
						{{ form.email.label }}
						{{ form.email() }}
					</div>
		
					<!-- Password input -->
					<div class="form-outline mb-2">
						{{ form.password.label }}
						{{ form.password() }}
					</div>
		
					<div class="d-flex justify-content-between align-items-center">
						<!-- Checkbox -->
						<div class="form-group form-check">
							{{ form.remember_me() }}
							{{ form.remember_me.label(class_='form-check-label') }}
						</div>
						<a href="#!" class="text-body">Забыли пароль?</a>
					</div>
					
					<!-- Submit-->
					<div class="text-center text-lg-start mt-4 pt-2">
						{{ form.submit() }}
						<p class="small fw-bold mt-2 pt-1 mb-0">У вас нет аккаунта?
							<a href="/users/registration" class="link-danger">Зарегистрироваться</a>
						</p>
					</div>
		
				</form>
			</div>
			</div>
		</div>
	</section>
{% endblock %}

webapp/templates/user/registration.html
{% extends "base.html" %}

{% block content %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% endwith %}
    <section class="vh-80">
        <div class="row d-flex justify-content-center align-items-center h-80">
            <div class="col-lg-10 col-xl-10">

                <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-4 col-xl-5 order-1 order-lg-1">

                    <p class="text-center h2 fw-bold mb-4 mx-1 mx-md-4 mt-4">Регистрация</p>
                    <form action="{{ url_for('user.process_reg') }}" method="POST" class="mx-1 mx-md-4">
                        {{ form.hidden_tag() }}

                        <!-- Name input -->
                        <div class="form-outline flex-fill mb-2">
                            {{ form.username.label }}
                            {{ form.username() }}
                        </div>
                    
                        <!-- Surname input -->
                        <div class="form-outline flex-fill mb-2">
                            {{ form.surname.label }}
                            {{ form.surname() }}
                        </div>

                        <!-- Organization input -->
                        <div class="form-outline flex-fill mb-2">
                            {{ form.organization.label }}
                            {{ form.organization() }}
                        </div>

                        <!-- Email input -->
                        <div class="form-outline flex-fill mb-2">
                            {{ form.email.label }}
                            {{ form.email() }}
                        </div>

                        <!-- Password input -->
                        <div class="form-outline mb-4">
                            {{ form.password.label }}
                            {{ form.password() }}
                        </div>

                        <!-- Submit -->
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                            {{ form.submit() }}
                        </div>

                    </form>

                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                        class="img-fluid" alt="Sample image">

                    </div>
                </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}