webapp/task/models.py
from webapp.db import db


class Tasks(db.Model):
    """
    Table of registered tasks for verification
    """
    id_task = db.Column(db.Integer, primary_key=True)
    id_user = db.Column(db.Integer, db.ForeignKey('user.id'))
    id_appr_type = db.Column(db.Integer,
                             db.ForeignKey('approved_types.id_appr_type'))
    model_mi = db.Column(db.String(512))
    serial_number = db.Column(db.Integer)
    protocol_number = db.Column(db.String(64))
    id_status = db.Column(db.Integer, db.ForeignKey('status_task.id_status'))


class Status_task(db.Model):
    """
    Table of task status names
    """
    id_status = db.Column(db.Integer, primary_key=True)
    status_name = db.Column(db.String(32))
    tasks = db.relationship('Tasks', backref='tasks_status', lazy='dynamic')

webapp/task/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, SubmitField

from wtforms.validators import DataRequired


class ManageTaskForm(FlaskForm):
    """
    Task management form
    """
    delete_submit = SubmitField(
        'Удалить',
        render_kw={"class": "border-0 btn-transition btn btn-outline-danger delete"}
    )
    change_submit = SubmitField(
        'Изменить',
        render_kw={"class": "border-0 btn-transition btn btn-outline-success change"}
    )
    create_submit = SubmitField(
        'Создать задание',
        render_kw={"class": "btn create-task"}
    )


class SearchTaskForm(FlaskForm):
    """
    Form for searching tasks
    """
    search_num = StringField(
        'Заводской номер',
        render_kw={"class": "form-control me-1",
                   "placeholder": "Заводской номер"}
    )
    search_submit = SubmitField(
        'Поиск',
        render_kw={"class": "btn btn-primary"}
    )


class CreateTaskForm(FlaskForm):
    """
    Verification task registration form
    """
    number_mi = StringField(
        'Номер в госреестре',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg item"}
    )
    name_mi = StringField(
        'Наименование СИ',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg item dis"}
    )
    designation_mi = StringField(
        'Тип СИ',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg item dis"}
    )
    model_mi = SelectField(
        'Модель (модификация) СИ',
        validators=[DataRequired()],
        choices=[],
        validate_choice=False,
        render_kw={"class": "form-select form-select-lg mb-3 item"}
    )
    serial_number = StringField(
        'Заводской (серийный) номер СИ',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg item"}
    )
    protocol_number = StringField(
        'Номер протокола',
        validators=[DataRequired()],
        render_kw={"class": "form-control form-control-lg item"}
    )
    submit = SubmitField(
        'Зарегистрировать задание',
        render_kw={"class": "btn btn-lg create-task"}
    )

webapp/task/views.py
import os
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user

from webapp.appr_type.models import Approved_types
from webapp.task.forms import CreateTaskForm, ManageTaskForm, SearchTaskForm
from webapp.task.models import Tasks, Status_task
from webapp.verification.scripts.json_parser import JsonHandler
from webapp.db import db


blueprint = Blueprint('tasks', __name__, url_prefix='/tasks')


@blueprint.route('/', methods=['GET'], defaults={"page": 1})
@blueprint.route('/<int:page>', methods=['GET'])
def task_manager(page):
    """
    This page is used to manage tasks and create new tasks.
    """
    per_page = 10
    title = "Задания на проведение поверки"
    manage_task_form = ManageTaskForm()
    search_task_form = SearchTaskForm()
    tasks_info = db.session.query(Tasks). \
        join(Status_task, Tasks.id_status == Status_task.id_status). \
        filter(Tasks.id_user == current_user.id). \
        paginate(page=page, per_page=per_page, error_out=False)

    return render_template(
        'tasks/task_manager.html',
        page_title=title,
        manage_task_form=manage_task_form,
        search_task_form=search_task_form,
        pagination=tasks_info
    )


@blueprint.route('/search/<string:search_num>/', methods=['GET'], defaults={"page": 1})
@blueprint.route('/search/<string:search_num>/<int:page>', methods=['GET'])
def search_task(search_num, page):
    """
    This page
    """
    per_page = 10
    title = "Задания на проведение поверки"
    manage_task_form = ManageTaskForm()
    search_task_form = SearchTaskForm()
    tasks_info = Tasks.query. \
        filter(Tasks.id_user == current_user.id). \
        filter(Tasks.serial_number.like(f'%{search_num}%')). \
        paginate(page=page, per_page=per_page, error_out=False)

    return render_template(
        'tasks/search_task.html',
        page_title=title,
        manage_task_form=manage_task_form,
        search_task_form=search_task_form,
        pagination=tasks_info,
        search_num=search_num
    )


@blueprint.route('/process-search', methods=['POST'])
def process_search():
    """
    This page
    """
    search_task_form = SearchTaskForm()
    if search_task_form.validate_on_submit():
        search_num = str(search_task_form.search_num.data)
        if search_num != '':
            return redirect(url_for('tasks.search_task',
                                    search_num=search_num,
                                    page=1))

    return redirect(url_for('tasks.task_manager'))


@blueprint.route('/create_task/<string:number_mi>')
def create_task(number_mi: str):
    """
    This page is used to register a verification task

    :param number_mi: number in the state register
    """
    title = 'Регистрация задания на проведение поверки'
    task_form = CreateTaskForm()
    appr_type_info = Approved_types.query. \
        filter(Approved_types.number_si == number_mi).first()
    file = f'webapp/appr_type/scripts/{number_mi}.json'
    if os.path.exists(file):
        data_file = JsonHandler(file)
        models = data_file.get_models()
    task_form.model_mi.choices = models

    return render_template(
        'tasks/new_task.html',
        page_title=title,
        appr_type_info=appr_type_info,
        form=task_form
    )


@blueprint.route('/process-reg-task', methods=['POST'])
def process_reg_task():
    """
    This page is used to register the task in the database
    """
    task_form = CreateTaskForm()
    appr_type_info = Approved_types.query. \
        filter(Approved_types.number_si == task_form.number_mi.data).first()
    if task_form.validate_on_submit():
        new_task = Tasks(
            id_user=current_user.id,
            id_appr_type=appr_type_info.id_appr_type,
            model_mi=task_form.model_mi.data,
            serial_number=task_form.serial_number.data,
            protocol_number=task_form.protocol_number.data,
            id_status=1
        )
        db.session.add(new_task)
        db.session.commit()
        flash(f"""
        Задание на поверку зарегистрировано!
        (Заводской (серийный) номер СИ: {task_form.serial_number.data};
        номер протокола: {task_form.protocol_number.data})
        """)

        return redirect(url_for(
            'verification.verification_mi',
            number_mi=task_form.number_mi.data,
            model=task_form.model_mi.data
        ))

    flash('Что-то пошло не так!')

    return redirect(url_for('main_page'))

webapp/templates/tasks/new_task.html
{% extends "base.html" %}

{% block content %}
	<div class="registration-form">
		<form action="{{ url_for('tasks.process_reg_task') }}" method="POST">
			{{ form.hidden_tag() }}
			
			<p class="h5 text-center">{{ page_title }}</p>
			<div class="form-icon">
				<a class="icon icon-user">
					<img src="/static/images/create-task.png" alt="" width="100" height="100">
				</a>
			</div>
			
			<div class="form-group">
				{{ form.number_mi.label }}
				{{ form.number_mi(value=appr_type_info.number_si) }}
			</div>
			<div class="form-group">
				{{ form.name_mi.label }}
				{{ form.name_mi(value=appr_type_info.name_si) }}
			</div>
			<div class="form-group">
				{{ form.designation_mi.label }}
				{{ form.designation_mi(value=appr_type_info.designation_si) }}
			</div>
			<div class="form-group">
				{{ form.model_mi.label }}
				{{ form.model_mi() }}
			</div>
			<div class="form-group">
				{{ form.serial_number.label }}
				{{ form.serial_number() }}
			</div>
			<div class="form-group">
				{{ form.protocol_number.label }}
				{{ form.protocol_number() }}
			</div>
			<div class="form-group">
				{{ form.submit() }}
			</div>
		</form>
	</div>
{% endblock %}

webapp/templates/tasks/search_task.html
<link rel="stylesheet" href="/static/css/tasks_style.css">
<link rel="stylesheet" href="/static/css/font-awesome.min.css">
{% extends "base.html" %}

{% block content %}
	{% with messages = get_flashed_messages() %}
		{% if messages %}
			<div class="alert alert-warning" role="alert">
				{% for message in messages %}
					{{ message }}<br>
				{% endfor %}
			</div>
		{% endif %}
	{% endwith %}
	<p></p>
	<div class="card-header-tab">
		<form class="d-flex search" action="{{ url_for('tasks.process_search') }}" method="POST">
			{{ search_task_form.hidden_tag() }}
				{{ search_task_form.search_num(value=search_num) }}
				{{ search_task_form.search_submit() }}
		</form>

		<nav aria-label="Page navigation" class="navigation_page">
			<ul class="pagination pagination-sm">
				<li class="page-item {% if not pagination.has_prev %} disabled {% endif %}">
					<a class="page-link" href="{{ url_for('tasks.search_task', search_num=search_num, page=pagination.prev_num) }}" aria-label="Предыдущая">
						<span aria-hidden="true">&laquo;</span>
					</a>
				</li>
		
				{% for page in pagination.iter_pages(left_edge=1, left_current=2, right_current=2, right_edge=1) %}
					{% if page %}
					<li class="page-item {%if page==pagination.page%} active {%endif%}">
						<a class="page-link" href="{{ url_for('tasks.search_task', search_num=search_num, page=page) }}">{{page}}</a>
					</li>
					{% else %}
					<li class="page-item disabled">
						<a class="page-link" href="#">&hellip;</a>
					</li>
					{% endif %}
				{% endfor %}
		
				<li class="page-item {% if not pagination.has_next %} disabled {% endif %}">
					<a class="page-link" href="{{ url_for('tasks.search_task', search_num=search_num, page=pagination.next_num) }}" aria-label="Следующая">
						<span aria-hidden="true">&raquo;</span>
					</a>
				</li>
			</ul>
		</nav>
	</div>
	<div class="row d-flex justify-content-center container">
		<div class="col">
			<div class="card-hover-shadow-2x card">
				<div class="card-header-tab card-header">
					<div class="d-block">
						{{ manage_task_form.create_submit() }}
					</div>
				</div>

				<div class="scroll-area-sm">
					<perfect-scrollbar class="ps-show-limits">
						<div style="position: static;" class="ps ps--active-y">
							<div class="ps-content">
								<ul class=" list-group list-group-flush">
									{% for task in pagination.items %}
										<li class="list-group-item">
											<div class="widget-content p-0">
												<div class="widget-content-wrapper">
													<div class="widget-content-left mr-2">
														<div class="custom-checkbox custom-control">
															<input class="custom-control-input" id="exampleCustomCheckbox12" type="checkbox">
															<label class="custom-control-label" for="exampleCustomCheckbox12">&nbsp;</label>
														</div>
													</div>
													<div class="widget-content-left">
														<div class="widget-heading">Задание № {{ task.id_task }} ({{ task.model_mi }}, зав. номер {{ task.serial_number }})
															{% if task.id_status == 1 %}
																<span class="badge rounded-pill bg-info text-dark">В работе</span>
															{% else %}
																<span class="badge rounded-pill bg-success">Выполнено</span>
															{% endif %}
														</div>
												</div>
												<div class="widget-content-right">
													<button class="border-0 btn-transition btn btn-outline-success">
														<i class="fa fa-check" aria-hidden="true"></i>
													</button>
													<button class="border-0 btn-transition btn btn-outline-danger">
														<i class="fa fa-trash"></i>
													</button>
												</div>
											</div>
										</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</perfect-scrollbar>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

webapp/templates/tasks/task_manager.html
<link rel="stylesheet" href="/static/css/tasks_style.css">
<link rel="stylesheet" href="/static/css/font-awesome.min.css">
{% extends "base.html" %}

{% block content %}
	{% with messages = get_flashed_messages() %}
		{% if messages %}
			<div class="alert alert-warning" role="alert">
				{% for message in messages %}
					{{ message }}<br>
				{% endfor %}
			</div>
		{% endif %}
	{% endwith %}
	<p></p>
	<div class="card-header-tab">
		<form class="d-flex search" action="{{ url_for('tasks.process_search') }}" method="POST">
			{{ search_task_form.hidden_tag() }}
				{{ search_task_form.search_num() }}
				{{ search_task_form.search_submit() }}
		</form>
	
		<nav aria-label="Page navigation" class="navigation_page">
			<ul class="pagination pagination-sm">
				<li class="page-item {% if not pagination.has_prev %} disabled {% endif %}">
					<a class="page-link" href="{{ url_for('tasks.task_manager', page=pagination.prev_num) }}" aria-label="<<">
						<span aria-hidden="true">&laquo;</span>
					</a>
				</li>
	
				{% for page in pagination.iter_pages(left_edge=1, left_current=2, right_current=2, right_edge=1) %}
					{% if page %}
					<li class="page-item {%if page==pagination.page%} active {%endif%}">
						<a class="page-link" href="{{ url_for('tasks.task_manager', page=page) }}">{{page}}</a>
					</li>
					{% else %}
					<li class="page-item disabled">
						<a class="page-link" href="#">&hellip;</a>
					</li>
					{% endif %}
				{% endfor %}
	
				<li class="page-item {% if not pagination.has_next %} disabled {% endif %}">
					<a class="page-link" href="{{ url_for('tasks.task_manager', page=pagination.next_num) }}" aria-label=">>">
						<span aria-hidden="true">&raquo;</span>
					</a>
				</li>
			</ul>
		</nav>
	</div>
	<div class="row d-flex justify-content-center container">
		<div class="col">
			<div class="card-hover-shadow-2x card">
				<div class="card-header-tab card-header">
					<div class="d-block">
						{{ manage_task_form.create_submit() }}
					</div>
				</div>

				<div class="scroll-area-sm">
					<perfect-scrollbar class="ps-show-limits">
						<div style="position: static;" class="ps ps--active-y">
							<div class="ps-content">
								<ul class=" list-group list-group-flush">
									{% for task in pagination.items %}
										<li class="list-group-item">
											<div class="widget-content p-0">
												<div class="widget-content-wrapper">
													<div class="widget-content-left mr-2">
														<div class="custom-checkbox custom-control">
															<input class="custom-control-input" id="exampleCustomCheckbox12" type="checkbox">
															<label class="custom-control-label" for="exampleCustomCheckbox12">&nbsp;</label>
														</div>
													</div>
													<div class="widget-content-left">
														<div class="widget-heading">Задание № {{ task.id_task }} ({{ task.model_mi }}, зав. номер {{ task.serial_number }})
															{% if task.id_status == 1 %}
																<span class="badge rounded-pill bg-info text-dark">В работе</span>
															{% else %}
																<span class="badge rounded-pill bg-success">Выполнено</span>
															{% endif %}
														</div>
													</div>
													<div class="widget-content-right">
														{{ manage_task_form.change_submit }}
														{{ manage_task_form.delete_submit() }}
													</div>
												</div>
										</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</perfect-scrollbar>
				</div>
			</div>
		</div>
	</div>
{% endblock %}